export type NavbarPage =
   | "home"
   | "profiles"
   | "groups"
   | "repository"
   | "repositorySubmit"
   | "repositoryPaper"
   | "repositoryEdit"
   | "messages"
   | "projects"
   | "events"
   | "help"
   | "jobs"
   | "privacy"
   | "terms"
   | "whiteboard"
   | "user"
   | "userSettings";
